services:
  - type: web
    name: take-the-red-pill
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python3 telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /
    autoDeploy: true
